#!/usr/bin/env python
from llm_grabbing_bringup.action_lib import move_to_position, close_gripper, open_gripper, reset_to_default_pose
from llm_grabbing_bringup.env import query_obj_position, query_obj_positions, distance
from llm_grabbing_bringup.arguments import get_config
from llm_grabbing_bringup.interfaces import setup_LMP
from llm_grabbing_bringup.utils import set_lmp_objects

def main():

    # # Put the yellow block in the plate that contains the red block
           
    # # grasp the yellow block
    # yellow_block_position = query_obj_position('yellow block')
    # move_to_position(yellow_block_position.x, yellow_block_position.y, yellow_block_position.z)
    # close_gripper()

    # # put into the found plate
    # plate_positions = query_obj_positions('plate')
    # red_block_position = query_obj_position('red block')
    # for plate_position in plate_positions:
    #     if distance(red_block_position, plate_position) < 0.1:
    #         red_block_plate = plate_position
    #         break
    # move_to_position(red_block_plate.x, red_block_plate.y, red_block_plate.z + 0.2)
    # open_gripper()

    # # back to default pose
    # reset_to_default_pose()


    config = get_config('rlbench')
    lmps = setup_LMP('test2', config, debug=False)
    ui = lmps['plan_ui']
    
    set_lmp_objects(lmps, ["plate_1", "plate_2", "yellow block", "red block"])
    ui('Put the yellow block in the plate that contains the red block')

if __name__ == '__main__':
    main()