lmp_config:
  env:
    test1:
      name:
        - 'eraser'
      link_name: 
        - 'link'
      joint_value: 
        - 0.36
    test2:
      name:
        - 'yellow_box'
      link_name: 
        - 'link'
      joint_value: 
        - 0.36
    test4:
      name:
        - 'yellow_box'
      link_name: 
        - 'link'
      joint_value: 
        - 0.36
    test6:
      name:
        - 'yellow_box'
        - 'yellow_box_0'
      link_name: 
        - 'link'
        - 'link'
      joint_value: 
        - 0.36
        - 0.36
  lmps:
    planner:
      prompt_fname: planner_prompt
      model: gpt-3.5-turbo
      max_tokens: 512
      temperature: 0
      query_prefix: '# Query: '
      query_suffix: '.'
      stop:
        - '# Query: '
        - 'objects = '
      maintain_session: False
      include_context: True
      has_return: False
      return_val_name: ret_val
      load_cache: True
    composer:
      prompt_fname: composer_prompt
      model: gpt-3.5-turbo
      max_tokens: 512
      temperature: 0
      query_prefix: '# Query: '
      query_suffix: '.'
      stop:
        - '# Query: '
        - 'objects ='
      maintain_session: False
      include_context: False
      has_return: False
      return_val_name: ret_val
      load_cache: True